@startuml

title __NOSQL-OPERATORS-HBASE's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.hbase {
    class gr.ds.unipi.noda.api.hbase.HBaseConnectionFactory {
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    class gr.ds.unipi.noda.api.hbase.HBaseConnectionManager {
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    class gr.ds.unipi.noda.api.hbase.HBaseConnector {
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    class gr.ds.unipi.noda.api.hbase.HBaseOperators {
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      abstract class gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.HBaseAggregateOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorAvg {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorCount {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorMax {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorMin {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorSum {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.comparisonOperators {
      abstract class gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.ComparisonOperator {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.comparisonOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.HBaseComparisonOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.comparisonOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorEqual {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.comparisonOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorGreaterThan {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.comparisonOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorGreaterThanEqual {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.comparisonOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorLessThan {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.comparisonOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorLessThanEqual {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.comparisonOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorNotEqual {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geoTemporalOperators {
      abstract class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.GeoTemporalOperator {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geoTemporalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.HBaseGeoTemporalOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geoTemporalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.OperatorInGeoTemporalCircle {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geoTemporalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.OperatorInGeoTemporalPolygon {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geoTemporalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.OperatorInGeoTemporalRectangle {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geoTextualOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTextualOperators.HBaseGeoTextualOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      abstract class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.GeographicalOperator {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.HBaseGeographicalOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.OperatorGeoNearestNeighbors {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.OperatorInGeoCircle {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.OperatorInGeoPolygon {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.OperatorInGeoRectangle {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      namespace customFilters {
        class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.CircleFilter {
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      namespace customFilters {
        class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.PolygonFilter {
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      namespace customFilters {
        class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.RectangleFilter {
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      namespace customFilters {
        namespace generated {
          class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.generated.CircleFilterProtos {
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      namespace customFilters {
        namespace generated {
          class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.generated.PolygonFilterProtos {
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.geoperators.geographicalOperators {
      namespace customFilters {
        namespace generated {
          class gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.generated.RectangleFilterProtos {
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.logicalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.logicalOperators.HBaseLogicalOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.logicalOperators {
      abstract class gr.ds.unipi.noda.api.hbase.filterOperator.logicalOperators.LogicalOperator {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.logicalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.logicalOperators.OperatorAnd {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.logicalOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.logicalOperators.OperatorOr {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace filterOperator.textualOperators {
      class gr.ds.unipi.noda.api.hbase.filterOperator.textualOperators.HBaseTextualOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace sortOperator {
      class gr.ds.unipi.noda.api.hbase.sortOperator.HBaseSortOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace sortOperator {
      class gr.ds.unipi.noda.api.hbase.sortOperator.OperatorAsc {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace sortOperator {
      class gr.ds.unipi.noda.api.hbase.sortOperator.OperatorDesc {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace sortOperator {
      abstract class gr.ds.unipi.noda.api.hbase.sortOperator.SortOperator {
      }
    }
  }
  

  gr.ds.unipi.noda.api.hbase.HBaseConnectionFactory -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlConnectionFactory
  gr.ds.unipi.noda.api.hbase.HBaseConnectionManager -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnectionManager
  gr.ds.unipi.noda.api.hbase.HBaseConnector .up.|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnector
  gr.ds.unipi.noda.api.hbase.HBaseOperators -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbOperators
  gr.ds.unipi.noda.api.hbase.HBaseOperators o-- gr.ds.unipi.noda.api.hbase.HBaseConnectionManager : hbaseConnectionManager
  gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator -up-|> gr.ds.unipi.noda.api.core.operators.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.hbase.aggregateOperator.HBaseAggregateOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.aggregateOperators.BaseAggregateOperatorFactory
  gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorAvg -up-|> gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator
  gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorCount -up-|> gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator
  gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorMax -up-|> gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator
  gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorMin -up-|> gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator
  gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorSum -up-|> gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.ComparisonOperator -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.HBaseComparisonOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.comparisonOperators.BaseComparisonOperatorFactory
  gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorEqual -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorGreaterThan -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorGreaterThanEqual -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorLessThan -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorLessThanEqual -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.OperatorNotEqual -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.GeoTemporalOperator -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.GeoTemporalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.HBaseGeoTemporalOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.BaseGeoTemporalOperatorFactory
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.OperatorInGeoTemporalCircle -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.GeoTemporalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.OperatorInGeoTemporalPolygon -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.GeoTemporalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.OperatorInGeoTemporalRectangle -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTemporalOperators.GeoTemporalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geoTextualOperators.HBaseGeoTextualOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTextualOperators.BaseGeoTextualOperatorFactory
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.GeographicalOperator -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geographicalOperators.GeographicalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.HBaseGeographicalOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geographicalOperators.BaseGeographicalOperatorFactory
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.OperatorGeoNearestNeighbors -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.GeographicalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.OperatorInGeoCircle -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.GeographicalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.OperatorInGeoPolygon -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.GeographicalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.OperatorInGeoRectangle -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.GeographicalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.CircleFilter -up-|> org.apache.hadoop.hbase.filter.FilterBase
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.CircleFilter o-- gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.generated.CircleFilterProtos.CircleFilter.Coordinates : centerCoordinates
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.PolygonFilter -up-|> org.apache.hadoop.hbase.filter.FilterBase
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.RectangleFilter -up-|> org.apache.hadoop.hbase.filter.FilterBase
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.RectangleFilter o-- gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.generated.RectangleFilterProtos.RectangleFilter.Coordinates : lowerCoordinates
  gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.RectangleFilter o-- gr.ds.unipi.noda.api.hbase.filterOperator.geoperators.geographicalOperators.customFilters.generated.RectangleFilterProtos.RectangleFilter.Coordinates : upperCoordinates
  gr.ds.unipi.noda.api.hbase.filterOperator.logicalOperators.HBaseLogicalOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.logicalOperators.BaseLogicalOperatorFactory
  gr.ds.unipi.noda.api.hbase.filterOperator.logicalOperators.LogicalOperator -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.logicalOperators.OperatorAnd -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.logicalOperators.OperatorOr -up-|> gr.ds.unipi.noda.api.hbase.filterOperator.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.hbase.filterOperator.textualOperators.HBaseTextualOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.textualOperators.BaseTextualOperatorFactory
  gr.ds.unipi.noda.api.hbase.sortOperator.HBaseSortOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.sortOperators.BaseSortOperatorFactory
  gr.ds.unipi.noda.api.hbase.sortOperator.OperatorAsc -up-|> gr.ds.unipi.noda.api.hbase.sortOperator.SortOperator
  gr.ds.unipi.noda.api.hbase.sortOperator.OperatorDesc -up-|> gr.ds.unipi.noda.api.hbase.sortOperator.SortOperator
  gr.ds.unipi.noda.api.hbase.sortOperator.SortOperator -up-|> gr.ds.unipi.noda.api.core.operators.sortOperators.SortOperator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
