@startuml

title __SORTOPERATORS's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.mongo {
    namespace sortOperators {
      class gr.ds.unipi.noda.api.mongo.sortOperators.MongoDBSortOperatorFactory {
          + newOperatorAsc()
          + newOperatorDesc()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    namespace sortOperators {
      class gr.ds.unipi.noda.api.mongo.sortOperators.OperatorAsc {
          {static} + newOperatorAsc()
          # getSortConditionNum()
          - OperatorAsc()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    namespace sortOperators {
      class gr.ds.unipi.noda.api.mongo.sortOperators.OperatorDesc {
          {static} + newOperatorDesc()
          # getSortConditionNum()
          - OperatorDesc()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    namespace sortOperators {
      abstract class gr.ds.unipi.noda.api.mongo.sortOperators.SortOperator {
          + getOperatorExpression()
          # SortOperator()
          {abstract} # getSortConditionNum()
      }
    }
  }
  

  gr.ds.unipi.noda.api.mongo.sortOperators.MongoDBSortOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.sortOperators.BaseSortOperatorFactory
  gr.ds.unipi.noda.api.mongo.sortOperators.OperatorAsc -up-|> gr.ds.unipi.noda.api.mongo.sortOperators.SortOperator
  gr.ds.unipi.noda.api.mongo.sortOperators.OperatorDesc -up-|> gr.ds.unipi.noda.api.mongo.sortOperators.SortOperator
  gr.ds.unipi.noda.api.mongo.sortOperators.SortOperator -up-|> gr.ds.unipi.noda.api.core.operators.sortOperators.SortOperator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
