@startuml

title __GEOTEMPORALOPERATORS's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geoTemporalOperators {
          abstract class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.BaseGeoTemporalOperatorFactory {
              {abstract} + newOperatorGeoTemporalNearestNeighbors()
              {abstract} + newOperatorInGeoTemporalCircleKm()
              {abstract} + newOperatorInGeoTemporalCircleMeters()
              {abstract} + newOperatorInGeoTemporalCircleMiles()
              {abstract} + newOperatorInGeoTemporalPolygon()
              {abstract} + newOperatorInGeoTemporalRectangle()
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geoTemporalOperators {
          abstract class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.GeoTemporalOperator {
              {static} + geoTemporalOperator : BaseGeoTemporalOperatorFactory
              - geographicalOperator : GeographicalOperator<T, U>
              - temporalFieldName : String
              # GeoTemporalOperator()
              # getGeographicalOperator()
              # getTemporalFieldName()
              # getTemporalType()
          }
        }
      }
    }
  }
  

  gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.GeoTemporalOperator .up.|> gr.ds.unipi.noda.api.core.operators.filterOperators.FilterOperator
  gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.GeoTemporalOperator o-- S : temporalType


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
