@startuml

title __NOSQLDB's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.core.nosqldb {
    abstract class gr.ds.unipi.noda.api.core.nosqldb.NoSqlConnectionFactory {
        {abstract} + closeConnection()
        {abstract} + closeConnections()
        {abstract} + noSqlDbOperators()
        # NoSqlConnectionFactory()
        {abstract} # getBaseAggregateOperatorFactory()
        {abstract} # getBaseComparisonOperatorFactory()
        {abstract} # getBaseGeoSpatialOperatorFactory()
        {abstract} # getBaseGeoTemporalOperatorFactory()
        {abstract} # getBaseGeoTextualOperatorFactory()
        {abstract} # getBaseLogicalOperatorFactory()
        {abstract} # getBaseSortOperatorFactory()
        {abstract} # getBaseTextualOperatorFactory()
        - setBaseOperators()
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.nosqldb {
    abstract class gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnectionManager {
        - connections : Map<NoSqlDbConnector<T>, T>
        {abstract} + closeConnection()
        {abstract} + closeConnections()
        + getConnection()
        # NoSqlDbConnectionManager()
        # getConnections()
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.nosqldb {
    interface gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnector {
        {abstract} + createConnection()
        {abstract} + equals()
        {abstract} + hashCode()
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.nosqldb {
    abstract class gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbOperators {
        - dataCollection : String
        - sparkSession : SparkSession
        {abstract} + aggregate()
        {abstract} + avg()
        {abstract} + count()
        {abstract} + distinct()
        {abstract} + filter()
        + getDataCollection()
        + getNoSqlDbConnector()
        + getSparkSession()
        {abstract} + groupBy()
        {abstract} + limit()
        {abstract} + max()
        {abstract} + min()
        {abstract} + printScreen()
        {abstract} + project()
        {abstract} + sort()
        {abstract} + sum()
        {abstract} + toDataframe()
        # NoSqlDbOperators()
    }
  }
  

  gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbOperators o-- gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnector : noSqlDbConnector


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
