@startuml

title __CONSTANTS's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.core.constants {
    enum AggregationKeywords {
      AVG
      COUNT
      COUNT_DISTINCT
      MAX
      MIN
      SUM
      name
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.constants {
    class gr.ds.unipi.noda.api.core.constants.Commons {
        {static} + BASE_PATH : String
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.constants {
    class gr.ds.unipi.noda.api.core.constants.StringPool {
        {static} + AMPERSAND : String
        {static} + AMPERSAND_ENCODED : String
        {static} + APOSTROPHE : String
        {static} + ASCII_TABLE : String[]
        {static} + AT : String
        {static} + AT_AND_STAR : String
        {static} + BACK_SLASH : String
        {static} + BETWEEN : String
        {static} + BLANK : String
        {static} + CARET : String
        {static} + CDATA_CLOSE : String
        {static} + CDATA_OPEN : String
        {static} + CLOSE_BRACKET : String
        {static} + CLOSE_CURLY_BRACE : String
        {static} + CLOSE_PARENTHESIS : String
        {static} + COLON : String
        {static} + COMMA : String
        {static} + COMMA_AND_SPACE : String
        {static} + CONTENT : String
        {static} + DASH : String
        {static} + DEFAULT_CHARSET_NAME : String
        {static} + DOLLAR : String
        {static} + DOLLAR_AND_OPEN_CURLY_BRACE : String
        {static} + DOUBLE_AMPERSAND : String
        {static} + DOUBLE_APOSTROPHE : String
        {static} + DOUBLE_BACK_SLASH : String
        {static} + DOUBLE_CLOSE_BRACKET : String
        {static} + DOUBLE_CLOSE_CURLY_BRACE : String
        {static} + DOUBLE_DASH : String
        {static} + DOUBLE_DOLLAR : String
        {static} + DOUBLE_EQUAL : String
        {static} + DOUBLE_OPEN_BRACKET : String
        {static} + DOUBLE_OPEN_CURLY_BRACE : String
        {static} + DOUBLE_PERIOD : String
        {static} + DOUBLE_PIPE : String
        {static} + DOUBLE_QUOTE : String
        {static} + DOUBLE_SLASH : String
        {static} + DOUBLE_SPACE : String
        {static} + DOUBLE_UNDERLINE : String
        {static} + EIGHT_STARS : String
        {static} + EMPTY_ARRAY : String[]
        {static} + EQUAL : String
        {static} + EXCLAMATION : String
        {static} + FALSE : String
        {static} + FORWARD_SLASH : String
        {static} + FOUR_SPACES : String
        {static} + GRAVE_ACCENT : String
        {static} + GREATER_THAN : String
        {static} + GREATER_THAN_OR_EQUAL : String
        {static} + INVERTED_EXCLAMATION : String
        {static} + INVERTED_QUESTION : String
        {static} + ISO_8859_1 : String
        {static} + IS_NOT_NULL : String
        {static} + IS_NULL : String
        {static} + LAQUO : String
        {static} + LAQUO_CHAR : String
        {static} + LESS_THAN : String
        {static} + LESS_THAN_OR_EQUAL : String
        {static} + LIKE : String
        {static} + MINUS : String
        {static} + NBSP : String
        {static} + NEW_LINE : String
        {static} + NOT_EQUAL : String
        {static} + NOT_LIKE : String
        {static} + NULL : String
        {static} + NULL_CHAR : String
        {static} + OPEN_BRACKET : String
        {static} + OPEN_CURLY_BRACE : String
        {static} + OPEN_PARENTHESIS : String
        {static} + OS_EOL : String
        {static} + PERCENT : String
        {static} + PERIOD : String
        {static} + PIPE : String
        {static} + PLUS : String
        {static} + POUND : String
        {static} + PRIME : String
        {static} + QUESTION : String
        {static} + QUOTE : String
        {static} + RAQUO : String
        {static} + RAQUO_CHAR : String
        {static} + RETURN : String
        {static} + RETURN_NEW_LINE : String
        {static} + SEMICOLON : String
        {static} + SLASH : String
        {static} + SPACE : String
        {static} + STAR : String
        {static} + TAB : String
        {static} + THREE_SPACES : String
        {static} + TILDE : String
        {static} + TRIPLE_PERIOD : String
        {static} + TRUE : String
        {static} + UNDERLINE : String
        {static} + UTC : String
        {static} + UTF8 : String
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
