@startuml

title __COMPARISONOPERATORS's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.mongo {
    namespace filterOperators.comparisonOperators {
      abstract class gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.ComparisonOperator {
          + getOperatorExpression()
          # ComparisonOperator()
          {abstract} # getOperatorJsonField()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.MongoDBComparisonOperatorFactory {
          + newOperatorEq()
          + newOperatorEq()
          + newOperatorEq()
          + newOperatorEq()
          + newOperatorEq()
          + newOperatorEq()
          + newOperatorEq()
          + newOperatorEq()
          + newOperatorGt()
          + newOperatorGt()
          + newOperatorGt()
          + newOperatorGt()
          + newOperatorGt()
          + newOperatorGt()
          + newOperatorGte()
          + newOperatorGte()
          + newOperatorGte()
          + newOperatorGte()
          + newOperatorGte()
          + newOperatorGte()
          + newOperatorLt()
          + newOperatorLt()
          + newOperatorLt()
          + newOperatorLt()
          + newOperatorLt()
          + newOperatorLt()
          + newOperatorLte()
          + newOperatorLte()
          + newOperatorLte()
          + newOperatorLte()
          + newOperatorLte()
          + newOperatorLte()
          + newOperatorNe()
          + newOperatorNe()
          + newOperatorNe()
          + newOperatorNe()
          + newOperatorNe()
          + newOperatorNe()
          + newOperatorNe()
          + newOperatorNe()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorEqual {
          {static} + newOperatorEqual()
          {static} + newOperatorEqual()
          {static} + newOperatorEqual()
          {static} + newOperatorEqual()
          {static} + newOperatorEqual()
          {static} + newOperatorEqual()
          {static} + newOperatorEqual()
          {static} + newOperatorEqual()
          # getOperatorJsonField()
          - OperatorEqual()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorGreaterThan {
          {static} + newOperatorGreaterThan()
          {static} + newOperatorGreaterThan()
          {static} + newOperatorGreaterThan()
          {static} + newOperatorGreaterThan()
          {static} + newOperatorGreaterThan()
          {static} + newOperatorGreaterThan()
          # getOperatorJsonField()
          - OperatorGreaterThan()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorGreaterThanEqual {
          {static} + newOperatorGreaterThanEqual()
          {static} + newOperatorGreaterThanEqual()
          {static} + newOperatorGreaterThanEqual()
          {static} + newOperatorGreaterThanEqual()
          {static} + newOperatorGreaterThanEqual()
          {static} + newOperatorGreaterThanEqual()
          # getOperatorJsonField()
          - OperatorGreaterThanEqual()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorLessThan {
          {static} + newOperatorLessThan()
          {static} + newOperatorLessThan()
          {static} + newOperatorLessThan()
          {static} + newOperatorLessThan()
          {static} + newOperatorLessThan()
          {static} + newOperatorLessThan()
          # getOperatorJsonField()
          - OperatorLessThan()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorLessThanEqual {
          {static} + newOperatorLessThanEqual()
          {static} + newOperatorLessThanEqual()
          {static} + newOperatorLessThanEqual()
          {static} + newOperatorLessThanEqual()
          {static} + newOperatorLessThanEqual()
          {static} + newOperatorLessThanEqual()
          # getOperatorJsonField()
          - OperatorLessThanEqual()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorNotEqual {
          {static} + newOperatorNotEqual()
          {static} + newOperatorNotEqual()
          {static} + newOperatorNotEqual()
          {static} + newOperatorNotEqual()
          {static} + newOperatorNotEqual()
          {static} + newOperatorNotEqual()
          {static} + newOperatorNotEqual()
          {static} + newOperatorNotEqual()
          # getOperatorJsonField()
          - OperatorNotEqual()
      }
    }
  }
  

  gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.ComparisonOperator -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.MongoDBComparisonOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.comparisonOperators.BaseComparisonOperatorFactory
  gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorEqual -up-|> gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorGreaterThan -up-|> gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorGreaterThanEqual -up-|> gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorLessThan -up-|> gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorLessThanEqual -up-|> gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.OperatorNotEqual -up-|> gr.ds.unipi.noda.api.mongo.filterOperators.comparisonOperators.ComparisonOperator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
