@startuml

title __COMPARISONOPERATORS's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace comparisonOperators {
        abstract class gr.ds.unipi.noda.api.core.operators.filterOperators.comparisonOperators.BaseComparisonOperatorFactory {
            {abstract} + newOperatorEq()
            {abstract} + newOperatorEq()
            {abstract} + newOperatorEq()
            {abstract} + newOperatorEq()
            {abstract} + newOperatorEq()
            {abstract} + newOperatorEq()
            {abstract} + newOperatorEq()
            {abstract} + newOperatorEq()
            {abstract} + newOperatorGt()
            {abstract} + newOperatorGt()
            {abstract} + newOperatorGt()
            {abstract} + newOperatorGt()
            {abstract} + newOperatorGt()
            {abstract} + newOperatorGt()
            {abstract} + newOperatorGte()
            {abstract} + newOperatorGte()
            {abstract} + newOperatorGte()
            {abstract} + newOperatorGte()
            {abstract} + newOperatorGte()
            {abstract} + newOperatorGte()
            {abstract} + newOperatorLt()
            {abstract} + newOperatorLt()
            {abstract} + newOperatorLt()
            {abstract} + newOperatorLt()
            {abstract} + newOperatorLt()
            {abstract} + newOperatorLt()
            {abstract} + newOperatorLte()
            {abstract} + newOperatorLte()
            {abstract} + newOperatorLte()
            {abstract} + newOperatorLte()
            {abstract} + newOperatorLte()
            {abstract} + newOperatorLte()
            {abstract} + newOperatorNe()
            {abstract} + newOperatorNe()
            {abstract} + newOperatorNe()
            {abstract} + newOperatorNe()
            {abstract} + newOperatorNe()
            {abstract} + newOperatorNe()
            {abstract} + newOperatorNe()
            {abstract} + newOperatorNe()
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace comparisonOperators {
        abstract class gr.ds.unipi.noda.api.core.operators.filterOperators.comparisonOperators.ComparisonOperator {
            {static} + comparisonOperator : BaseComparisonOperatorFactory
            - fieldName : String
            # ComparisonOperator()
            # getFieldName()
            # getFieldValue()
        }
      }
    }
  }
  

  gr.ds.unipi.noda.api.core.operators.filterOperators.comparisonOperators.ComparisonOperator .up.|> gr.ds.unipi.noda.api.core.operators.filterOperators.FilterOperator
  gr.ds.unipi.noda.api.core.operators.filterOperators.comparisonOperators.ComparisonOperator o-- U : fieldValue


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
