@startuml

title __GR.DS.UNIPI.NODA.API.NEO4J's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.neo4j {
    class gr.ds.unipi.noda.api.neo4j.Neo4jConnectionFactory {
        + closeConnection()
        + closeConnections()
        + noSqlDbOperators()
        # getBaseAggregateOperatorFactory()
        # getBaseComparisonOperatorFactory()
        # getBaseGeoSpatialOperatorFactory()
        # getBaseGeoTemporalOperatorFactory()
        # getBaseGeoTextualOperatorFactory()
        # getBaseLogicalOperatorFactory()
        # getBaseSortOperatorFactory()
        # getBaseTextualOperatorFactory()
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    class gr.ds.unipi.noda.api.neo4j.Neo4jConnectionManager {
        {static} - INSTANCE : Neo4jConnectionManager
        + closeConnection()
        + closeConnections()
        {static} + getInstance()
        - Neo4jConnectionManager()
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    class gr.ds.unipi.noda.api.neo4j.Neo4jConnector {
        - addresses : List<Entry<String, Integer>>
        - authToken : AuthToken
        - config : Config
        - encryptionWithoutLocalhost : Boolean
        - typeOfConnection : String
        + createConnection()
        + equals()
        + hashCode()
        {static} + newNeo4jConnector()
        - Neo4jConnector()
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    class gr.ds.unipi.noda.api.neo4j.Neo4jOperators {
        - hasAlreadyAggregate : Boolean
        - hasGroupBy : Boolean
        - isTypeOfResultsList : Boolean
        - matchConstant : String
        - sb : StringBuilder
        + aggregate()
        + avg()
        + count()
        + distinct()
        + filter()
        + groupBy()
        + limit()
        + max()
        + min()
        + printScreen()
        + project()
        + sort()
        + sum()
        + toDataframe()
        {static} ~ newNeo4jOperators()
        - Neo4jOperators()
    }
  }
  

  gr.ds.unipi.noda.api.neo4j.Neo4jConnectionFactory -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlConnectionFactory
  gr.ds.unipi.noda.api.neo4j.Neo4jConnectionManager -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnectionManager
  gr.ds.unipi.noda.api.neo4j.Neo4jConnector .up.|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnector
  gr.ds.unipi.noda.api.neo4j.Neo4jOperators -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbOperators
  gr.ds.unipi.noda.api.neo4j.Neo4jOperators o-- gr.ds.unipi.noda.api.neo4j.Neo4jConnectionManager : neo4jConnectionManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
