@startuml

title __GEOMETRIES's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geometries {
          class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Circle {
              - radius : double
              + getCircleCenter()
              + getMbr()
              + getRadius()
              {static} + newCircle()
              - Circle()
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geometries {
          abstract class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Geometry {
              ~ latitudeOutOfRange : Predicate<Double>
              ~ longitudeOutOfRange : Predicate<Double>
              - coordinatesArray : Coordinates[]
              + getCoordinatesArray()
              {abstract} + getMbr()
              # Geometry()
              # checkCoordinates()
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geometries {
          class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Point {
              + getMbr()
              + getPoint()
              {static} + newPoint()
              - Point()
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geometries {
          class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Polygon {
              + getMbr()
              {static} + newPolygon()
              # Polygon()
              # checkCoordinates()
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geometries {
          class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Rectangle {
              + getLowerBound()
              + getMbr()
              + getUpperBound()
              {static} + newRectangle()
              - Rectangle()
              - Rectangle()
          }
        }
      }
    }
  }
  

  gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Circle -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Geometry
  gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Point -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Geometry
  gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Polygon -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Geometry
  gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Rectangle -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geometries.Geometry


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
