@startuml

title __SORTOPERATOR's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.hbase {
    namespace sortOperator {
      class gr.ds.unipi.noda.api.hbase.sortOperator.OperatorAsc {
          {static} + newOperatorAsc()
          - OperatorAsc()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace sortOperator {
      class gr.ds.unipi.noda.api.hbase.sortOperator.OperatorDesc {
          {static} + newOperatorDesc()
          - OperatorDesc()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace sortOperator {
      abstract class gr.ds.unipi.noda.api.hbase.sortOperator.SortOperator {
          + getOperatorExpression()
          # SortOperator()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace sortOperator {
      class gr.ds.unipi.noda.api.hbase.sortOperator.YYYDataBaseSortOperatorFactory {
          + newOperatorAsc()
          + newOperatorDesc()
      }
    }
  }
  

  gr.ds.unipi.noda.api.hbase.sortOperator.OperatorAsc -up-|> gr.ds.unipi.noda.api.hbase.sortOperator.SortOperator
  gr.ds.unipi.noda.api.hbase.sortOperator.OperatorDesc -up-|> gr.ds.unipi.noda.api.hbase.sortOperator.SortOperator
  gr.ds.unipi.noda.api.hbase.sortOperator.SortOperator -up-|> gr.ds.unipi.noda.api.core.operators.sortOperators.SortOperator
  gr.ds.unipi.noda.api.hbase.sortOperator.YYYDataBaseSortOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.sortOperators.BaseSortOperatorFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
