@startuml

title __OPERATORS's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.core.operators {
    class gr.ds.unipi.noda.api.core.operators.AggregateOperators {
        {static} + avg()
        {static} + count()
        {static} + countDistinct()
        {static} + countNonNull()
        {static} + max()
        {static} + min()
        {static} + sum()
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    class gr.ds.unipi.noda.api.core.operators.FilterOperators {
        {static} + allKeywords()
        {static} + and()
        {static} + anyKeywords()
        {static} + eq()
        {static} + eq()
        {static} + eq()
        {static} + eq()
        {static} + eq()
        {static} + eq()
        {static} + eq()
        {static} + eq()
        {static} + geoNearestNeighbors()
        {static} + geoTemporalNearestNeighbors()
        {static} + gt()
        {static} + gt()
        {static} + gt()
        {static} + gt()
        {static} + gt()
        {static} + gt()
        {static} + gte()
        {static} + gte()
        {static} + gte()
        {static} + gte()
        {static} + gte()
        {static} + gte()
        {static} + inGeoCircleKm()
        {static} + inGeoCircleMeters()
        {static} + inGeoCircleMiles()
        {static} + inGeoPolygon()
        {static} + inGeoRectangle()
        {static} + inGeoTemporalCircleKm()
        {static} + inGeoTemporalCircleMeters()
        {static} + inGeoTemporalCircleMiles()
        {static} + inGeoTemporalPolygon()
        {static} + inGeoTemporalRectangle()
        {static} + inGeoTextualCircleKm()
        {static} + inGeoTextualCircleMeters()
        {static} + inGeoTextualCircleMiles()
        {static} + inGeoTextualPolygon()
        {static} + inGeoTextualRectangle()
        {static} + lt()
        {static} + lt()
        {static} + lt()
        {static} + lt()
        {static} + lt()
        {static} + lt()
        {static} + lte()
        {static} + lte()
        {static} + lte()
        {static} + lte()
        {static} + lte()
        {static} + lte()
        {static} + ne()
        {static} + ne()
        {static} + ne()
        {static} + ne()
        {static} + ne()
        {static} + ne()
        {static} + ne()
        {static} + ne()
        {static} + or()
        {static} + topRankInGeoTextualCircleKm()
        {static} + topRankInGeoTextualCircleMeters()
        {static} + topRankInGeoTextualCircleMiles()
        {static} + topRankInGeoTextualPolygon()
        {static} + topRankInGeoTextualRectangle()
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    interface gr.ds.unipi.noda.api.core.operators.Operator {
        {abstract} + getOperatorExpression()
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    class gr.ds.unipi.noda.api.core.operators.SortOperators {
        {static} + asc()
        {static} + desc()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
