@startuml

title __TEMPORAL's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geoTemporalOperators {
          namespace temporal {
            class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.temporal.SingleTemporalValue {
                + getSingleTemporalValue()
                {static} + newSingleTemporalValue()
                - SingleTemporalValue()
            }
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geoTemporalOperators {
          namespace temporal {
            abstract class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.temporal.Temporal {
                - dates : Date[]
                # Temporal()
                # getDates()
            }
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geoTemporalOperators {
          namespace temporal {
            class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.temporal.TemporalBounds {
                + getLowerBound()
                + getUpperBound()
                {static} + newTemporalBounds()
                # TemporalBounds()
            }
          }
        }
      }
    }
  }
  

  gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.temporal.SingleTemporalValue -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.temporal.Temporal
  gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.temporal.TemporalBounds -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geoTemporalOperators.temporal.Temporal


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
