@startuml

title __AGGREGATEOPERATOR's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      abstract class gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator {
          + getOperatorExpression()
          # AggregateOperator()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.HBaseAggregateOperatorFactory {
          + newOperatorAvg()
          + newOperatorCount()
          + newOperatorCountDistinct()
          + newOperatorCountNonNull()
          + newOperatorMax()
          + newOperatorMin()
          + newOperatorSum()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorAvg {
          {static} + newOperatorAvg()
          - OperatorAvg()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorCount {
          {static} + newOperatorCount()
          - OperatorCount()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorMax {
          {static} + newOperatorMax()
          - OperatorMax()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorMin {
          {static} + newOperatorMin()
          - OperatorMin()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.hbase {
    namespace aggregateOperator {
      class gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorSum {
          {static} + newOperatorSum()
          - OperatorSum()
      }
    }
  }
  

  gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator -up-|> gr.ds.unipi.noda.api.core.operators.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.hbase.aggregateOperator.HBaseAggregateOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.aggregateOperators.BaseAggregateOperatorFactory
  gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorAvg -up-|> gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator
  gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorCount -up-|> gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator
  gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorMax -up-|> gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator
  gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorMin -up-|> gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator
  gr.ds.unipi.noda.api.hbase.aggregateOperator.OperatorSum -up-|> gr.ds.unipi.noda.api.hbase.aggregateOperator.AggregateOperator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
