@startuml

title __LOGICALOPERATORS's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.redisearch {
    namespace filterOperators {
      namespace logicalOperators {
        abstract class gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.LogicalOperator {
            + getPostOperatorExpression()
            {abstract} # getPostOperatorField()
            ~ LogicalOperator()
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.redisearch {
    namespace filterOperators {
      namespace logicalOperators {
        class gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.OperatorAnd {
            + getOperatorExpression()
            # getPostOperatorField()
            {static} ~ newOperatorAnd()
            - OperatorAnd()
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.redisearch {
    namespace filterOperators {
      namespace logicalOperators {
        class gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.OperatorOr {
            + getOperatorExpression()
            # getPostOperatorField()
            {static} ~ newOperatorOr()
            - OperatorOr()
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.redisearch {
    namespace filterOperators {
      namespace logicalOperators {
        class gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.RediSearchLogicalOperatorFactory {
            + newOperatorAnd()
            + newOperatorOr()
        }
      }
    }
  }
  

  gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.LogicalOperator .up.|> gr.ds.unipi.noda.api.redisearch.filterOperators.RediSearchPostFilterOperator
  gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.LogicalOperator -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.OperatorAnd -up-|> gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.OperatorOr -up-|> gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.redisearch.filterOperators.logicalOperators.RediSearchLogicalOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.logicalOperators.BaseLogicalOperatorFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
