@startuml

title __NOSQL-OPERATORS-NEO4J's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.neo4j {
    class gr.ds.unipi.noda.api.neo4j.Neo4jConnectionFactory {
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    class gr.ds.unipi.noda.api.neo4j.Neo4jConnectionManager {
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    class gr.ds.unipi.noda.api.neo4j.Neo4jConnector {
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    class gr.ds.unipi.noda.api.neo4j.Neo4jOperators {
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      abstract class gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.Neo4jAggregateOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorAvg {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCount {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCountDistinct {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCountNonNull {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorMax {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorMin {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorSum {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.comparisonOperators {
      abstract class gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.ComparisonOperator {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.Neo4jComparisonOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorEqual {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorGreaterThan {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorGreaterThanEqual {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorLessThan {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorLessThanEqual {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.comparisonOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorNotEqual {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.geoperators.geographicalOperators {
      abstract class gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.GeographicalOperator {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.geoperators.geographicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.Neo4JGeographicalOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.geoperators.geographicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.OperatorGeoNearestNeighbors {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.geoperators.geographicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.OperatorInGeographicalCircle {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.geoperators.geographicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.OperatorInGeographicalPolygon {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.geoperators.geographicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.OperatorInGeographicalRectangle {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.logicalOperators {
      abstract class gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.LogicalOperator {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.logicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.Neo4jLogicalOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.logicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.OperatorAnd {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.logicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.OperatorOr {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace sortOperators {
      class gr.ds.unipi.noda.api.neo4j.sortOperators.Neo4jSortOperatorFactory {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace sortOperators {
      class gr.ds.unipi.noda.api.neo4j.sortOperators.OperatorAsc {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace sortOperators {
      class gr.ds.unipi.noda.api.neo4j.sortOperators.OperatorDesc {
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace sortOperators {
      abstract class gr.ds.unipi.noda.api.neo4j.sortOperators.SortOperator {
      }
    }
  }
  

  gr.ds.unipi.noda.api.neo4j.Neo4jConnectionFactory -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlConnectionFactory
  gr.ds.unipi.noda.api.neo4j.Neo4jConnectionManager -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnectionManager
  gr.ds.unipi.noda.api.neo4j.Neo4jConnector .up.|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnector
  gr.ds.unipi.noda.api.neo4j.Neo4jOperators -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbOperators
  gr.ds.unipi.noda.api.neo4j.Neo4jOperators o-- gr.ds.unipi.noda.api.neo4j.Neo4jConnectionManager : neo4jConnectionManager
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator -up-|> gr.ds.unipi.noda.api.core.operators.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.Neo4jAggregateOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.aggregateOperators.BaseAggregateOperatorFactory
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorAvg -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCount -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCountDistinct -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCountNonNull -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorMax -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorMin -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorSum -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.ComparisonOperator -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.Neo4jComparisonOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.comparisonOperators.BaseComparisonOperatorFactory
  gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorEqual -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorGreaterThan -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorGreaterThanEqual -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorLessThan -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorLessThanEqual -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.OperatorNotEqual -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.comparisonOperators.ComparisonOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.GeographicalOperator -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geographicalOperators.GeographicalOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.Neo4JGeographicalOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geographicalOperators.BaseGeographicalOperatorFactory
  gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.OperatorGeoNearestNeighbors -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.GeographicalOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.OperatorInGeographicalCircle -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.GeographicalOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.OperatorInGeographicalPolygon -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.GeographicalOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.OperatorInGeographicalRectangle -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.geoperators.geographicalOperators.GeographicalOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.LogicalOperator -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.Neo4jLogicalOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.logicalOperators.BaseLogicalOperatorFactory
  gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.OperatorAnd -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.OperatorOr -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.neo4j.sortOperators.Neo4jSortOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.sortOperators.BaseSortOperatorFactory
  gr.ds.unipi.noda.api.neo4j.sortOperators.OperatorAsc -up-|> gr.ds.unipi.noda.api.neo4j.sortOperators.SortOperator
  gr.ds.unipi.noda.api.neo4j.sortOperators.OperatorDesc -up-|> gr.ds.unipi.noda.api.neo4j.sortOperators.SortOperator
  gr.ds.unipi.noda.api.neo4j.sortOperators.SortOperator -up-|> gr.ds.unipi.noda.api.core.operators.sortOperators.SortOperator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
