@startuml

title __MONGO's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.mongo {
    class gr.ds.unipi.noda.api.mongo.MongoDBConnectionFactory {
        + closeConnection()
        + closeConnections()
        + noSqlDbOperators()
        # getBaseAggregateOperatorFactory()
        # getBaseComparisonOperatorFactory()
        # getBaseGeoSpatialOperatorFactory()
        # getBaseGeoTemporalOperatorFactory()
        # getBaseGeoTextualOperatorFactory()
        # getBaseLogicalOperatorFactory()
        # getBaseSortOperatorFactory()
        # getBaseTextualOperatorFactory()
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    class gr.ds.unipi.noda.api.mongo.MongoDBConnectionManager {
        {static} - INSTANCE : MongoDBConnectionManager
        + closeConnection()
        + closeConnections()
        {static} + getInstance()
        - MongoDBConnectionManager()
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    class gr.ds.unipi.noda.api.mongo.MongoDBConnector {
        - addresses : List<Entry<String, Integer>>
        - mongoClientOptions : MongoClientOptions
        - mongoCredential : MongoCredential
        + createConnection()
        + equals()
        + getDatabase()
        + getHost()
        + getMongoURIForSparkSession()
        + getPassword()
        + getPort()
        + getUsername()
        + hashCode()
        {static} + newMongoDBConnector()
        - MongoDBConnector()
    }
  }
  

  namespace gr.ds.unipi.noda.api.mongo {
    class gr.ds.unipi.noda.api.mongo.MongoDBOperators {
        - database : String
        - groupByAgg : List<Entry<List<String>, List<AggregateOperator>>>
        - stagesList : List<Bson>
        - uriSparkSession : String
        + aggregate()
        + avg()
        + count()
        + distinct()
        + filter()
        + groupBy()
        + limit()
        + max()
        + min()
        + printScreen()
        + project()
        + sort()
        + sum()
        + toDataframe()
        {static} ~ newMongoDBOperators()
        - MongoDBOperators()
    }
  }
  

  gr.ds.unipi.noda.api.mongo.MongoDBConnectionFactory -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlConnectionFactory
  gr.ds.unipi.noda.api.mongo.MongoDBConnectionManager -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnectionManager
  gr.ds.unipi.noda.api.mongo.MongoDBConnector .up.|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbConnector
  gr.ds.unipi.noda.api.mongo.MongoDBOperators -up-|> gr.ds.unipi.noda.api.core.nosqldb.NoSqlDbOperators
  gr.ds.unipi.noda.api.mongo.MongoDBOperators o-- gr.ds.unipi.noda.api.mongo.MongoDBConnectionManager : mongoDBConnectionManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
