@startuml

title __AGGREGATEOPERATORS's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      abstract class gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator {
          + getOperatorExpression()
          # AggregateOperator()
          {abstract} # getAggregateOperatorField()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.Neo4jAggregateOperatorFactory {
          + newOperatorAvg()
          + newOperatorCount()
          + newOperatorCountDistinct()
          + newOperatorCountNonNull()
          + newOperatorMax()
          + newOperatorMin()
          + newOperatorSum()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorAvg {
          {static} + newOperatorAvg()
          # getAggregateOperatorField()
          - OperatorAvg()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCount {
          {static} + newOperatorCount()
          # getAggregateOperatorField()
          - OperatorCount()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCountDistinct {
          {static} + newOperatorCountDistinct()
          # getAggregateOperatorField()
          - OperatorCountDistinct()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCountNonNull {
          {static} + newOperatorCountNonNull()
          # getAggregateOperatorField()
          - OperatorCountNonNull()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorMax {
          {static} + newOperatorMax()
          # getAggregateOperatorField()
          - OperatorMax()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorMin {
          {static} + newOperatorMin()
          # getAggregateOperatorField()
          - OperatorMin()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace aggregateOperators {
      class gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorSum {
          {static} + newOperatorSum()
          # getAggregateOperatorField()
          - OperatorSum()
      }
    }
  }
  

  gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator -up-|> gr.ds.unipi.noda.api.core.operators.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.Neo4jAggregateOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.aggregateOperators.BaseAggregateOperatorFactory
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorAvg -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCount -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCountDistinct -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorCountNonNull -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorMax -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorMin -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator
  gr.ds.unipi.noda.api.neo4j.aggregateOperators.OperatorSum -up-|> gr.ds.unipi.noda.api.neo4j.aggregateOperators.AggregateOperator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
