@startuml

title __GEOGRAPHICALOPERATORS's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geographicalOperators {
          abstract class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geographicalOperators.BaseGeographicalOperatorFactory {
              {abstract} + newOperatorGeoNearestNeighbors()
              {abstract} + newOperatorInGeoCircle()
              {abstract} + newOperatorInGeoPolygon()
              {abstract} + newOperatorInGeoRectangle()
          }
        }
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.core.operators {
    namespace filterOperators {
      namespace geoperators {
        namespace geographicalOperators {
          abstract class gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geographicalOperators.GeographicalOperator {
              {static} + geoSpatialOperator : BaseGeographicalOperatorFactory
              - fieldName : String
              + getGeometry()
              # GeographicalOperator()
              # getFieldName()
          }
        }
      }
    }
  }
  

  gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geographicalOperators.GeographicalOperator .up.|> gr.ds.unipi.noda.api.core.operators.filterOperators.FilterOperator
  gr.ds.unipi.noda.api.core.operators.filterOperators.geoperators.geographicalOperators.GeographicalOperator o-- U : geometry


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
