@startuml

title __LOGICALOPERATORS's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.logicalOperators {
      abstract class gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.LogicalOperator {
          + getOperatorExpression()
          # LogicalOperator()
          {abstract} ~ getLogicalOperatorType()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.logicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.Neo4jLogicalOperatorFactory {
          + newOperatorAnd()
          + newOperatorOr()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.logicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.OperatorAnd {
          {static} + newOperatorAnd()
          # getLogicalOperatorType()
          - OperatorAnd()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.neo4j {
    namespace filterOperators.logicalOperators {
      class gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.OperatorOr {
          {static} + newOperatorOr()
          # getLogicalOperatorType()
          - OperatorOr()
      }
    }
  }
  

  gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.LogicalOperator -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.Neo4jLogicalOperatorFactory -up-|> gr.ds.unipi.noda.api.core.operators.filterOperators.logicalOperators.BaseLogicalOperatorFactory
  gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.OperatorAnd -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.LogicalOperator
  gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.OperatorOr -up-|> gr.ds.unipi.noda.api.neo4j.filterOperators.logicalOperators.LogicalOperator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
