@startuml

title __REDISEARCH's Class Diagram__\n

  namespace gr.ds.unipi.noda.api.client {
    namespace redisearch {
      class gr.ds.unipi.noda.api.client.redisearch.RediSearchBuilderFactory {
          + Builder()
          + Builder()
          + Builder()
          + Builder()
          + Builder()
          + Builder()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.client {
    namespace redisearch {
      class gr.ds.unipi.noda.api.client.redisearch.RediSearchSystem {
          + getDefaultPort()
          # getConnector()
          {static} ~ initPoolConfig()
          - RediSearchSystem()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.client {
    namespace redisearch {
      class gr.ds.unipi.noda.api.client.redisearch.RediSearchSystem.Builder {
          - clientName : String
          - connectionTimeout : int
          - database : int
          - hostnameVerifier : HostnameVerifier
          - password : String
          - poolConfig : JedisPoolConfig
          - poolSize : int
          - soTimeout : int
          - ssl : boolean
          - sslParameters : SSLParameters
          - sslSocketFactory : SSLSocketFactory
          + Builder()
          + Builder()
          + Builder()
          + build()
          + clientName()
          + connectionTimeout()
          + database()
          + hostnameVerifier()
          + password()
          + soTimeout()
          + ssl()
          + sslParameters()
          + sslSocketFactory()
          + timeout()
          # self()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.client {
    namespace redisearch {
      class gr.ds.unipi.noda.api.client.redisearch.RediSearchSystemSentinels {
          + getDefaultPort()
          # getConnector()
          - RediSearchSystemSentinels()
      }
    }
  }
  

  namespace gr.ds.unipi.noda.api.client {
    namespace redisearch {
      class gr.ds.unipi.noda.api.client.redisearch.RediSearchSystemSentinels.Builder {
          - clientName : String
          - connectionTimeout : int
          - database : int
          - masterName : String
          - password : String
          - poolConfig : JedisPoolConfig
          - poolSize : int
          - soTimeout : int
          + Builder()
          + Builder()
          + Builder()
          + build()
          + clientName()
          + connectionTimeout()
          + database()
          + password()
          + soTimeout()
          + timeout()
          # self()
      }
    }
  }
  

  gr.ds.unipi.noda.api.client.redisearch.RediSearchSystem -up-|> gr.ds.unipi.noda.api.client.NoSqlDbSystem
  gr.ds.unipi.noda.api.client.redisearch.RediSearchSystem o-- gr.ds.unipi.noda.api.redisearch.RediSearchConnector : connector
  gr.ds.unipi.noda.api.client.redisearch.RediSearchSystem +-down- gr.ds.unipi.noda.api.client.redisearch.RediSearchSystem.Builder
  gr.ds.unipi.noda.api.client.redisearch.RediSearchSystem.Builder -up-|> gr.ds.unipi.noda.api.client.NoSqlDbSystem.Builder
  gr.ds.unipi.noda.api.client.redisearch.RediSearchSystemSentinels -up-|> gr.ds.unipi.noda.api.client.NoSqlDbSystem
  gr.ds.unipi.noda.api.client.redisearch.RediSearchSystemSentinels o-- gr.ds.unipi.noda.api.redisearch.RediSearchConnector : connector
  gr.ds.unipi.noda.api.client.redisearch.RediSearchSystemSentinels +-down- gr.ds.unipi.noda.api.client.redisearch.RediSearchSystemSentinels.Builder
  gr.ds.unipi.noda.api.client.redisearch.RediSearchSystemSentinels.Builder -up-|> gr.ds.unipi.noda.api.client.NoSqlDbSystem.Builder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
